### ISSUE TITLE
Lab Structure

### ISSUE THREAD

**Issue by carlskii** [jetstack/cert-manager-nginx-plus-lab#12]
Whilst the LAB works very well, I feel that it almost too short. Based on the fact we will start the instruction from the point of a working `Kubectl`, Im concerned the lab will get completed in 5-10 mins. 

I think we need to spend more time initially explaining/dissecting/showing each of the `cert-manager` components. i.e. What it is, how it works etc including its use of CRD's etc.

I think we could also do with a section that walks the attendees through some basic troubleshooting steps. e.g. what if the cert-request fails.

Also, we should spend some time explaining more about the K8s architecture in which cert-manager interoperates with. e.g. what an ingress controller is and how it works? What is a work-load ? Why are machine identities important etc. 

Carl

**Comment by meyskens** [comment]
Going to close this as a lot more is added now (and we have extra slides)
